# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://47.102.124.165:3306/api-hu?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver