# 各个环境的公共配置放在这里

# 指定多环境配置文件(maven动态切换)#spring.profiles.active#
spring:
  profiles:
    active: dev-local

mybatis:
  configuration:
    # mybatis打印sql(配合MyBatis Log Plugin插件可以在控制台查看格式化并且填充了占位符的SQL语句)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# log configuration
logging:
  file:
    name: logs/api-hu.log
