# 线上服务器开发联调测试环境（非生产、非纯测试环境）

# 配置数据源信息
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Aliyun_rds_123456
        url: jdbc:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/project-seed-4?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: keqi
        hikari:
            pool-name: hikari

# 配置日志文件
logging:
    level:
        com.keqi: debug
        # org.springframework.web: debug

knife4j:
    enable: true