server:
  port: 9092
  servlet:
    context-path: /seed

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aliyun_rds_123456
    url: jdbc:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/043-project-seed-2?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: keqi
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

logging:
  file:
    name: logs/app.log
  level:
    com:
      keqi: info

mybatis:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl